/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package my.slots;


import javax.swing.ImageIcon;
import java.util.ArrayList;

/**
 *
 * @author s-milligand
 */
public class SlotsUI extends javax.swing.JFrame {
    private SlotMachine s;

    /**
     * Creates new form SlotsUI
     */
    public SlotsUI() {
        initComponents();
        s = new SlotMachine();
        jLabel2.setText("0");
    }
    public SlotsUI(int money){
        initComponents();
        s = new SlotMachine(money);
        jLabel2.setText(money+"");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(200, 200));

        jLabel1.setText("Coins:");

        jButton1.setText("Spin!");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("jLabel2");

        jLabel3.setText("Wager:");

        jLabel4.setText("jLabel4");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/slots/box.png"))); // NOI18N
        jLabel5.setMinimumSize(new java.awt.Dimension(30, 30));
        jLabel5.setName(""); // NOI18N

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/slots/box.png"))); // NOI18N

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/slots/box.png"))); // NOI18N

        jButton2.setText("Switch to BlackJack");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel8.setText("Cherry         2       8 ");

        jLabel9.setText("Strawberry  4       16");

        jLabel10.setText("Seven          7       28");

        jLabel11.setText("Dollar           21     121");

        jLabel12.setText("Gold             50     250");

        jLabel13.setText("Diamond      147   597");

        jLabel14.setText("Bankrupt!    -69    All Your Money!");

        jLabel15.setText("Acuskev      1000   1000000");

        jLabel16.setText("2 in-a-row");

        jLabel17.setText("3 in-a-row");

        jLabel18.setText("$5 to play!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)
                                .addGap(95, 95, 95)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(320, 320, 320)
                                .addComponent(jButton1)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jLabel7))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 175, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(83, 83, 83))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(324, 324, 324)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel18)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(356, 356, 356)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel17)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(jButton1))
                        .addGap(54, 54, 54))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        ArrayList<String> trio;
        trio = new ArrayList<String>();
        s.addMoney(-5);        
        for(int i=0; i<3; i++){
            String it = s.getSlot();
           // System.out.println("swag" + it);
            switch (it) {
                case "cherry":
                    trio.add("cherry");
                    if(i==0){
                        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/slots/pics/cherr.jpg")));                    }
                    if(i==1){
                       jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/slots/pics/cherr.jpg")));
                   }if(i==2){
                       jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/slots/pics/cherr.jpg")));
                   }break;
                case "strawberry":
                    trio.add("strawberry");
                    if(i==0){
                        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/slots/pics/strawberr.jpg")));                    }
                    if(i==1){
                       jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/slots/pics/strawberr.jpg")));
                   }if(i==2){
                       jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/slots/pics/strawberr.jpg")));
                   }break;
                case "seven":
                    trio.add("seven");
                    if(i==0){
                        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/slots/pics/seven.jpg")));                    }
                    if(i==1){
                       jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/slots/pics/seven.jpg")));
                   }if(i==2){
                       jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/slots/pics/seven.jpg")));
                   }break;
                case "gold":
                    trio.add("gold");
                    if(i==0){
                        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/slots/pics/gold.jpg")));                    }
                    if(i==1){
                       jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/slots/pics/gold.jpg")));
                   }if(i==2){
                       jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/slots/pics/gold.jpg")));
                   }break;
                case "diamond":
                    trio.add("diamond");
                    if(i==0){
                        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/slots/pics/diamond.jpg")));                    }
                    if(i==1){
                       jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/slots/pics/diamond.jpg")));
                   }if(i==2){
                       jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/slots/pics/diamond.jpg")));
                   }break;
                case "dollar":
                    trio.add("dollar");
                    if(i==0){
                        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/slots/pics/dollar.jpg")));                    }
                    if(i==1){
                       jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/slots/pics/dollar.jpg")));
                   }if(i==2){
                       jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/slots/pics/dollar.jpg")));
                   }break;
                case "bad":
                    trio.add("bad");
                    if(i==0){
                        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/slots/pics/bad.jpg")));                    }
                    if(i==1){
                       jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/slots/pics/bad.jpg")));
                   }if(i==2){
                       jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/slots/pics/bad.jpg")));
                   }break;
                case "acuskev":
                    trio.add("acuskev");
                    if(i==0){
                        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/slots/pics/acuskev.jpg")));                    }
                    if(i==1){
                       jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/slots/pics/acuskev.jpg")));
                   }if(i==2){
                       jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/slots/pics/acuskev.jpg")));
                   }break;  
            }
        }
        //s.addMoney(69);
        //System.out.println(trio.get(1));
        //jLabel2.setText(s.getMoney()+"");
        //if(trio.size()!=3){
         //   System.out.println(trio.size());
         //   for(String e: trio)
         //       System.out.println(e);
       // }
        
        if(trio.get(0).equals(trio.get(1))&&trio.get(0).equals(trio.get(2))){
            switch (trio.get(0)) {
                case "cherry":
                    s.addMoney(8);
                    break;
                case "strawberry":
                    s.addMoney(16);
                    break;
                case "seven":
                    s.addMoney(28);
                    break;
                case "gold":
                    s.addMoney(250);
                    break;
                case "diamond":
                    s.addMoney(597);
                    break;
                case "dollar":
                    s.addMoney(121);
                    break;
                case "bad":
                    s.addMoney(-(s.getMoney()));
                    break;
                case "acuskev":
                    s.addMoney(1000000);
                    break;
            }
        }
        else if(trio.get(0).equals(trio.get(1))||trio.get(0).equals(trio.get(2))){
            switch (trio.get(0)) {
                case "cherry":
                    s.addMoney(2);
                    break;
                case "strawberry":
                    s.addMoney(4);
                    break;
                case "seven":
                    s.addMoney(7);
                    break;
                case "gold":
                    s.addMoney(50);
                    break;
                case "diamond":
                    s.addMoney(147);
                    break;
                case "dollar":
                    s.addMoney(21);
                    break;
                case "bad":
                    s.addMoney(-69);
                    break;
                case "acuskev":
                    s.addMoney(1000);
                    break;
            }            
        }else if(trio.get(1).equals(trio.get(2))){
            switch (trio.get(1)) {
                case "cherry":
                    s.addMoney(2);
                    break;
                case "strawberry":
                    s.addMoney(4);
                    break;
                case "seven":
                    s.addMoney(7);
                    break;
                case "gold":
                    s.addMoney(50);
                    break;
                case "diamond":
                    s.addMoney(147);
                    break;
                case "dollar":
                    s.addMoney(21);
                    break;
                case "bad":
                    s.addMoney(-69);
                    break;
                case "acuskev":
                    s.addMoney(1000);
                    break;
            }
        }
        jLabel2.setText(s.getMoney()+"");
          
              
       // jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/slots/pics/acuskev.jpg")));
       
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setVisible(false);
        new BlackJackUI(s.getMoney()).setVisible(true);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SlotsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SlotsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SlotsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SlotsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new SlotsUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
